//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetCore6.Localization.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetCore6.Localization.Shared.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الالغاء مسبقا.
        /// </summary>
        public static string AlreadyCanceled {
            get {
                return ResourceManager.GetString("AlreadyCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا العنصر موجود من قبل.
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفواً لا يمكنك ارسال المبيعات.
        /// </summary>
        public static string CanNotSendSIC {
            get {
                return ResourceManager.GetString("CanNotSendSIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ من فضلك حاول لاحقاً.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفواً هذا العنصر محذوف بالفعل.
        /// </summary>
        public static string ItemAlreadyRemoved {
            get {
                return ResourceManager.GetString("ItemAlreadyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الخانات اكثر من المطلوب.
        /// </summary>
        public static string MaxDigitValidation {
            get {
                return ResourceManager.GetString("MaxDigitValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الحروف اكثر من المطلوب.
        /// </summary>
        public static string MaxLengthValidation {
            get {
                return ResourceManager.GetString("MaxLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الحروف اقل من المطلوب.
        /// </summary>
        public static string MinLengthValidation {
            get {
                return ResourceManager.GetString("MinLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Not Allowed to $feature$.
        /// </summary>
        public static string NOT_AUTHORIZE_USER {
            get {
                return ResourceManager.GetString("NOT_AUTHORIZE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to Edit  This Deliveryman.
        /// </summary>
        public static string NOTAUTHORiZEDbRANCHMANGER {
            get {
                return ResourceManager.GetString("NOTAUTHORiZEDbRANCHMANGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجي التحقق من الايميل.
        /// </summary>
        public static string SendPassword {
            get {
                return ResourceManager.GetString("SendPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الاضافة بنجاح.
        /// </summary>
        public static string SuccessfullyCreated {
            get {
                return ResourceManager.GetString("SuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف بنجاح.
        /// </summary>
        public static string SuccessfullyDeleted {
            get {
                return ResourceManager.GetString("SuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسجيل الخروج بنجاح.
        /// </summary>
        public static string SuccessfullyLoggedOut {
            get {
                return ResourceManager.GetString("SuccessfullyLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تجديد الطلب بنجاح.
        /// </summary>
        public static string SuccessfullyRenewedRequest {
            get {
                return ResourceManager.GetString("SuccessfullyRenewedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنجاح.
        /// </summary>
        public static string SuccessfullySaved {
            get {
                return ResourceManager.GetString("SuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعديل بنجاح.
        /// </summary>
        public static string SuccessfullyUpdated {
            get {
                return ResourceManager.GetString("SuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم رفع الملف بنجاح.
        /// </summary>
        public static string SuccessfullyUploaded {
            get {
                return ResourceManager.GetString("SuccessfullyUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم اضافه الطلب الي الرحلة.
        /// </summary>
        public static string YouSuccessfullyAddedOrderToTrip {
            get {
                return ResourceManager.GetString("YouSuccessfullyAddedOrderToTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل الترتيب بنجاح.
        /// </summary>
        public static string YouSuccessfullyUpdatedDisplayOrder {
            get {
                return ResourceManager.GetString("YouSuccessfullyUpdatedDisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل الحالة بنجاح.
        /// </summary>
        public static string YouSuccessfullyUpdatedStatus {
            get {
                return ResourceManager.GetString("YouSuccessfullyUpdatedStatus", resourceCulture);
            }
        }
    }
}
