//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetCore6.Localization.User {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetCore6.Localization.User.UserResource", typeof(UserResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry , cannot get user details.
        /// </summary>
        public static string CannotGetUserDetails {
            get {
                return ResourceManager.GetString("CannotGetUserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال رابط التفعيل إلي البريد الالكترونى .
        /// </summary>
        public static string CheckEmail {
            get {
                return ResourceManager.GetString("CheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الحالية غير صحيحة.
        /// </summary>
        public static string CurrentPasswordNotValid {
            get {
                return ResourceManager.GetString("CurrentPasswordNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo Request Send Succssfully.
        /// </summary>
        public static string DemoRequestSendSuccssfully {
            get {
                return ResourceManager.GetString("DemoRequestSendSuccssfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفواً البريد الالكتروني مستخدم من قبل.
        /// </summary>
        public static string EmailAlreadyExists2 {
            get {
                return ResourceManager.GetString("EmailAlreadyExists2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تأكيد الايميل.
        /// </summary>
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذ الايميل غير موجود.
        /// </summary>
        public static string EmailNotExists {
            get {
                return ResourceManager.GetString("EmailNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry , email or mobile already exists..
        /// </summary>
        public static string EmailOrMobileExists {
            get {
                return ResourceManager.GetString("EmailOrMobileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ اثناء تسجيل الدخول.
        /// </summary>
        public static string ErrorOccurredWhileLogging {
            get {
                return ResourceManager.GetString("ErrorOccurredWhileLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفواً حدث خطأ اثناء ارسال رابط استعادة كلمة المرور.
        /// </summary>
        public static string ErrorOccurredWhileSendingResetLink {
            get {
                return ResourceManager.GetString("ErrorOccurredWhileSendingResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفواً الحساب الخاص بك موقوف مؤقتاً.
        /// </summary>
        public static string InActiveAccount {
            get {
                return ResourceManager.GetString("InActiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفواً كود التفعيل غير صحيح او منتهي.
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry , invalid email or password..
        /// </summary>
        public static string InvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("InvalidEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المحمول أو كلمة المرور غير صحيحة.
        /// </summary>
        public static string InvalidMobileOrPassword {
            get {
                return ResourceManager.GetString("InvalidMobileOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الدخول السريع غير صحيح.
        /// </summary>
        public static string InvalidQRCode {
            get {
                return ResourceManager.GetString("InvalidQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الدخول أو كلمة المرور غير صحيحة.
        /// </summary>
        public static string InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفواً رقم الموبايل مستخدم من قبل.
        /// </summary>
        public static string MobileAlreadyExists {
            get {
                return ResourceManager.GetString("MobileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفواً رقم المحمول غير مستخدم من قبل.
        /// </summary>
        public static string MobileNotExists {
            get {
                return ResourceManager.GetString("MobileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تكون كلمة المرور الجديدة مختلفة عن القديمة.
        /// </summary>
        public static string NewPasswordMustBeDifferentFromTheOld {
            get {
                return ResourceManager.GetString("NewPasswordMustBeDifferentFromTheOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد صلاحيات لهذا المستخدم.
        /// </summary>
        public static string NoModules {
            get {
                return ResourceManager.GetString("NoModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير كلمة المرور بنجاح.
        /// </summary>
        public static string PasswordChangedSuccssfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccssfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم ارسال رابط استعادة كلمة المرور على حسابك.
        /// </summary>
        public static string ResetLinkSent {
            get {
                return ResourceManager.GetString("ResetLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم ارسال كلمة السر.
        /// </summary>
        public static string SendPassword {
            get {
                return ResourceManager.GetString("SendPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تفعيل الحساب بنجاح.
        /// </summary>
        public static string SuccessfullyActivated {
            get {
                return ResourceManager.GetString("SuccessfullyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسجيل الدخول بنجاح.
        /// </summary>
        public static string SuccessfullyLoggedIn {
            get {
                return ResourceManager.GetString("SuccessfullyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسجيل الخروج بنجاح.
        /// </summary>
        public static string SuccessfullyLoggedOut {
            get {
                return ResourceManager.GetString("SuccessfullyLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفواً اسم الدخول مستخدم من قبل.
        /// </summary>
        public static string UserNameAlreadyExists {
            get {
                return ResourceManager.GetString("UserNameAlreadyExists", resourceCulture);
            }
        }
    }
}
